import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Shirt, User, Loader2, AlertCircle } from "lucide-react";
import { AvatarViewer } from "@/components/AvatarViewer";
import { z } from "zod";
import { getErrorMessage, useJobStatus } from "@/lib/api";
import { Button } from "@/components/ui/button";

const processingSearchSchema = z.object({
  jobId: z.string().min(1),
});

export const Route = createFileRoute("/processing")({
  validateSearch: processingSearchSchema,
  head: () => ({
    meta: [
      { title: "Generating — FitCheck AI" },
      { name: "description", content: "Your virtual try-on is being generated by AI." },
    ],
  }),
  component: ProcessingPage,
});

function ProcessingPage() {
  const navigate = useNavigate();
  const { jobId } = Route.useSearch();
  const { data: job, isLoading, isError, error } = useJobStatus(jobId);
  const [done, setDone] = useState(false);

  useEffect(() => {
    if (!job) return;

    if (job.status === "completed") {
      setDone(true);
      const timeout = window.setTimeout(() => {
        navigate({
          to: "/results",
          search: { jobId },
        });
      }, 2000);
      return () => window.clearTimeout(timeout);
    }

    if (job.status === "failed") {
      setDone(false);
    }
  }, [job, jobId, navigate]);

  const progress = job?.progress ?? 0;
  const stageLabel =
    job?.stage ??
    (job?.status === "queued" ? "Waiting to start…" : "Processing your try-on…");

  if (!jobId) {
    return (
      <ProcessingMessage
        title="No job in progress"
        description="Start a new try-on to generate a look."
        action={
          <Link to="/try-on">
            <Button>Go to Try-On</Button>
          </Link>
        }
      />
    );
  }

  if (isLoading && !job) {
    return (
      <ProcessingMessage
        title="Loading job…"
        description="Fetching your generation status."
        icon={<Loader2 className="h-8 w-8 animate-spin text-copper" />}
      />
    );
  }

  if (isError) {
    return (
      <ProcessingMessage
        title="Could not load job"
        description={getErrorMessage(error)}
        icon={<AlertCircle className="h-8 w-8 text-destructive" />}
        action={
          <Link to="/try-on">
            <Button variant="outline">Back to Try-On</Button>
          </Link>
        }
      />
    );
  }

  if (job?.status === "failed") {
    return (
      <ProcessingMessage
        title="Generation failed"
        description="Something went wrong while creating your look. Please try again."
        icon={<AlertCircle className="h-8 w-8 text-destructive" />}
        action={
          <Link to="/try-on">
            <Button>Try Again</Button>
          </Link>
        }
      />
    );
  }

  return (
    <div className="flex min-h-[70vh] flex-col items-center justify-center px-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md text-center"
      >
        <AnimatePresence mode="wait">
          {!done ? (
            <motion.div
              key="avatar"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.5 }}
              className="mb-8 flex justify-center"
            >
              <div className="h-[400px] w-[400px]">
                <AvatarViewer />
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="result"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5 }}
              className="mb-8 flex justify-center"
            >
              <div className="h-[400px] w-[400px] overflow-hidden rounded-2xl border border-border shadow-sm">
                <img src={job?.result_url || ""} alt="Result" className="h-full w-full object-cover" />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <h2 className="font-heading text-2xl font-bold text-foreground">
          {done ? "Done!" : "Generating Your Look"}
        </h2>

        <AnimatePresence mode="wait">
          {!done && (
            <motion.p
              key={stageLabel}
              initial={{ opacity: 0, y: 5 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -5 }}
              transition={{ duration: 0.3 }}
              className="mt-2 capitalize text-muted-foreground"
            >
              {stageLabel}
            </motion.p>
          )}
        </AnimatePresence>

        <div className="mt-8 h-1.5 w-full overflow-hidden rounded-full bg-secondary">
          <motion.div
            className="h-full rounded-full bg-copper"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.3, ease: "linear" }}
          />
        </div>
        <p className="mt-2 text-xs text-muted-foreground">{Math.round(progress)}%</p>

        {!done && (
          <div className="mt-10 flex items-center justify-center gap-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
              <User className="h-6 w-6" />
            </div>
            <div className="h-px w-8 bg-border" />
            <motion.div
              animate={{ rotate: [0, 5, -5, 0] }}
              transition={{ duration: 2, repeat: Infinity }}
              className="flex h-16 w-16 items-center justify-center rounded-xl bg-secondary text-muted-foreground"
            >
              <Shirt className="h-6 w-6" />
            </motion.div>
          </div>
        )}
      </motion.div>
    </div>
  );
}

function ProcessingMessage({
  title,
  description,
  icon,
  action,
}: {
  title: string;
  description: string;
  icon?: React.ReactNode;
  action?: React.ReactNode;
}) {
  return (
    <div className="flex min-h-[70vh] flex-col items-center justify-center px-4">
      <div className="max-w-md text-center">
        {icon && <div className="mb-4 flex justify-center">{icon}</div>}
        <h2 className="font-heading text-2xl font-bold text-foreground">{title}</h2>
        <p className="mt-2 text-muted-foreground">{description}</p>
        {action && <div className="mt-6 flex justify-center">{action}</div>}
      </div>
    </div>
  );
}
