/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as StylistRouteImport } from './routes/stylist'
import { Route as SizeRouteImport } from './routes/size'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeRoute = SizeRouteImport.update({
  id: '/size',
  path: '/size',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/colors': typeof ColorsRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/stylist': typeof StylistRoute
  '/try-on': typeof TryOnRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/colors': typeof ColorsRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/stylist': typeof StylistRoute
  '/try-on': typeof TryOnRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/colors': typeof ColorsRoute
  '/feed': typeof FeedRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size': typeof SizeRoute
  '/stylist': typeof StylistRoute
  '/try-on': typeof TryOnRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/colors'
    | '/feed'
    | '/history'
    | '/login'
    | '/processing'
    | '/results'
    | '/sitemap.xml'
    | '/size'
    | '/stylist'
    | '/try-on'
    | '/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/colors'
    | '/feed'
    | '/history'
    | '/login'
    | '/processing'
    | '/results'
    | '/sitemap.xml'
    | '/size'
    | '/stylist'
    | '/try-on'
    | '/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/colors'
    | '/feed'
    | '/history'
    | '/login'
    | '/processing'
    | '/results'
    | '/sitemap.xml'
    | '/size'
    | '/stylist'
    | '/try-on'
    | '/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  ColorsRoute: typeof ColorsRoute
  FeedRoute: typeof FeedRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeRoute: typeof SizeRoute
  StylistRoute: typeof StylistRoute
  TryOnRoute: typeof TryOnRoute
  WardrobeRoute: typeof WardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size': {
      id: '/size'
      path: '/size'
      fullPath: '/size'
      preLoaderRoute: typeof SizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  ColorsRoute: ColorsRoute,
  FeedRoute: FeedRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeRoute: SizeRoute,
  StylistRoute: StylistRoute,
  TryOnRoute: TryOnRoute,
  WardrobeRoute: WardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
